plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.3'
    id 'io.spring.dependency-management' version '1.1.6'
}

ext {
    springAiVersion = "1.0.0-M2"
    springCloudVersion = "2023.0.3"
}

group = 'com.spring'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.hibernate.orm:hibernate-core:6.2.0.Final'
    implementation platform("org.springframework.ai:spring-ai-bom:1.0.0-SNAPSHOT")
    implementation 'org.springframework.ai:spring-ai-openai'
    implementation 'org.springframework.ai:spring-ai-openai-spring-boot-starter'
    // json
    implementation 'org.json:json:20240303'
//    // AWS SDK BOM 추가 (최신 버전 사용)
//    implementation(platform("software.amazon.awssdk:bom:2.21.1"))
//    // Amazon S3 의존성 추가
//    implementation("software.amazon.awssdk:s3")
    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
    implementation 'software.amazon.awssdk:ssm:2.17.89'


    // webClient
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    //AWS Parameter Store
    implementation platform("io.awspring.cloud:spring-cloud-aws-dependencies:3.2.0")
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs'

    implementation 'io.awspring.cloud:spring-cloud-aws-starter-parameter-store'

    implementation 'org.antlr:antlr4:4.13.1'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    // 제미나이
    implementation 'com.google.cloud:google-cloud-vertexai:0.4.0'
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    // openfeign
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'


    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    //h2
    runtimeOnly 'com.h2database:h2'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
    }
}


tasks.named('test') {
    useJUnitPlatform()
}
